# This template contains steps to create a darwin framework bundle

parameters:
  image: ''

jobs:
- job: framework
  displayName: Darwin Frameworks
  variables:
  - name: runCodesignValidationInjection
    value: false
  - name: skipComponentGovernanceDetection
    value: true
  workspace:
    clean: all
  pool:
    vmImage: ${{ parameters.image }}
  steps:
  - checkout: self

  - template: ./download-artifacts.yml
    parameters:
      platform: macos
      arch: universal
      tls: openssl

  - template: ./download-artifacts.yml
    parameters:
      platform: ios
      arch: arm64
      tls: openssl

  - task: PowerShell@2
    displayName: macOS Framework
    inputs:
      pwsh: true
      filePath: scripts/package-darwin-framework.ps1
      arguments: -Config Release -Platform macos -Arch universal

  - task: PowerShell@2
    displayName: iOS Framework
    inputs:
      pwsh: true
      filePath: scripts/package-darwin-framework.ps1
      arguments: -Config Release -Platform ios -Arch arm64

  - task: CopyFiles@2
    displayName: Move Distribution
    inputs:
      sourceFolder: artifacts/dist
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: Upload Distribution
    inputs:
      artifactName: distribution
      pathToPublish: $(Build.ArtifactStagingDirectory)
      parallel: true
