#
# Continuous Integration (CI)
# This pipeline builds and runs MsQuic performance tests.
#

trigger: none
pr: none

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

parameters:
- name: kernelmode
  type: boolean
  displayName: Kernel Mode
  default: false
- name: mode
  type: string
  displayName: Mode
  default: Normal
  values:
  - Normal
  - PGO
  - Record
  - RecordQUICTrace
- name: testTypes
  type: string
  displayName: Test Types
  default: Remote,Loopback

#
# Builds
#

stages:

- stage: build_windows
  displayName: Build Windows
  dependsOn: []
  variables:
    runCodesignValidationInjection: false
  jobs:
  # Officially supported configurations.
  - template: ./templates/build-config-winkernel.yml
    parameters:
      arch: x64
      config: Release
  - template: ./templates/build-config-user.yml
    parameters:
      image: windows-latest
      platform: windows
      arch: x64
      tls: schannel
      config: Release
      extraBuildArgs: -DisableTest -DisableTools

#
# Performance Tests
#

- stage: performance
  displayName: Performance Testing (${{ parameters.mode }})
  dependsOn:
  - build_windows
  jobs:
  - template: ./templates/run-performance.yml
    parameters:
      pool: MsQuic-Win-Perf
      platform: windows
      localTls: schannel
      remoteTls: schannel
      extraArgs: -RecordQUIC
